a= int(input("Enter the first number: "))
b= int(input("Enter the second number: "))
add=a+b
sub=a-b
pro=a*b
divi=a/b
print("Addition=",add)
print("Subtraction=",sub)
print("Multiplication=",pro)
print("Division=",divi)
